export const WallFloor = [
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FHerbarium%20of%20Extinct%20Plants%2Fimage-thumb__34159__header_fullscreen_2x_jpg%2FHerbarium-of-Extinct-Plants-250.webp&w=3840&q=80",
    itemname: "Herbarium of Extinct Plants Carpet ",
    brandName: "by moooi",
    price: "$250",
    availability: "In Stock",
    type: "Wall&Floor",
    category: "Carpets",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FLinesLinesLines%2FProduct%20Shots%2F81972%2Fimage-thumb__81972__header_fullscreen_2x_jpg%2FMoooi-Carpets-LinesLinesLines-By-Alf-Product_1.webp&w=1080&q=80      ",
    itemname: "LinesLinesLines Carpet ",
    brandName: "by Alf Bärbel Wit",
    price: "$250",
    availability: "In Stock",
    type: "Wall&Floor",
    category: "Carpets",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FDropshadow%20Transparant%20Background%2Fimage-thumb__14276__header_fullscreen_2x_jpg%2FMalmaison_Aquamarine_160043_160047.webp&w=3840&q=80      ",
    itemname: "Malmaison Carpet ",
    brandName: "by Christian Lacroix Maison",
    price: "$250",
    availability: "In Stock",
    type: "Wall&Floor",
    category: "Carpets",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FSprouts%2Fimage-thumb__26502__header_fullscreen_2x_jpg%2FSprouts-Carpet.webp&w=1080&q=80",
    itemname: "Sprouts Carpet ",
    brandName: "by Kiki van Eijk",
    price: "$250",
    availability: "In Stock",
    type: "Wall&Floor",
    category: "Carpets",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FIn%20The%20Meadow%2Fimage-thumb__37764__header_fullscreen_2x_jpg%2FEmbryo-II-200x264-300DPI.jpg&w=1080&q=80",
    itemname: "In the Meadow Carpet ",
    brandName: "by Emma Larsson",
    price: "$250",
    availability: "In Stock",
    type: "Wall&Floor",
    category: "Carpets",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FExtinct%20Animals%20Carpet%2Fimage-thumb__62969__header_fullscreen_2x_jpg%2FQueen-Cobra-Carpet-Hero-V2.webp&w=3840&q=80",
    itemname: "Extinct Animal Carpet ",
    brandName: "by ADA SOKÓŁ, 2023",
    price: "$250",
    availability: "In Stock",
    category: "Carpets",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FDropshadow%20Transparant%20Background%2Fimage-thumb__14333__header_fullscreen_2x_jpg%2FUrbanMandalas_Mexico_250cm_S170009.webp&w=3840&q=80",
    itemname: "Urban Mandalas Carpet ",
    brandName: "by Neal Peterson",
    price: "$250",
    availability: "In Stock",
    type: "Wall&Floor",
    category: "Carpets",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FBisanto%2Fimage-thumb__36884__header_fullscreen_2x_jpg%2FADRIANO-Carpet.jpg&w=1080&q=80 ",
    itemname: "Bisanto Carpet",
    brandName: "by Antonio Aricò",
    price: "$250",
    availability: "In Stock",
    type: "Wall&Floor",
    category: "Carpets",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FDropshadow%20Transparant%20Background%2FLiquid%20Layers%20Carpet%20Collection%2Fimage-thumb__31419__header_fullscreen_2x_jpg%2FMarl-250.webp&w=3840&q=80",
    itemname: "Liquid Layers Carpet ",
    brandName: "by Claire Vos",
    price: "$250",
    availability: "In Stock",
    type: "Wall&Floor",
    category: "Carpets",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FWallcovering%2Ftokyo%20blue%2Frendezvoustokyoblue%2Fimage-thumb__17212__header_fullscreen_2x_jpg%2Fmoooiwallcoveringtokyoblue-rendezvoustokyoblue-mo3010-m2.webp&w=3840&q=80",
    itemname: "Rendezvous Tokyo printed Carpet ",
    brandName: "by moooi",
    price: "$250",
    availability: "In Stock",
    type: "Wall&Floor",
    category: "Carpets",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FRendezvous-Tokyo-Blue%2Fimage-thumb__24598__header_fullscreen_2x_jpg%2FRendezvous-indigo-200x300-300dpi.webp&w=1080&q=80",
    itemname: "Rendezvous Tokyo Blue Carpet ",
    brandName: "by moooi",
    price: "$250",
    availability: "In Stock",
    type: "Wall&Floor",
    category: "Carpets",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FDropshadow%20Transparant%20Background%2FSpace%20Escape%20Carpet%20Collection%2F17838%2Fimage-thumb__17838__header_fullscreen_2x_jpg%2FElena-Salmistraro-Reptilian-300dpi.webp&w=1080&q=80",
    itemname: "Space Escape Carpet ",
    brandName: "by Moooi Crapets",
    price: "$250",
    availability: "In Stock",
    type: "Wall&Floor",
    category: "Carpets",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FWallcovering%2Fmemento%20moooi%20medley%2Fimage-thumb__46683__header_fullscreen_2x_jpg%2FMoooiWallcoveringMementoMoooi_MementoMoooiMedley_MO4032_Mood_Web_HR.webp&w=3840&q=80",
    itemname: "Memento Moooi Medley Wallcovering ",
    brandName: "by moooi",
    price: "$250",
    availability: "In Stock",
    type: "Wall&Floor",
    category: "Wallcovering",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FWallcovering%2Fdandelion%20cranes%2Fimage-thumb__46658__header_fullscreen_2x_jpg%2FMoooiWallcoveringMementoMoooi_DandelionCranes_MO4021_Mood_Web_HR.webp&w=3840&q=80",
    itemname: "Dandelion Cranes WallcoveringL ",
    price: "$250",
    brandName: "by moooi",
    availability: "In Stock",
    type: "Wall&Floor",
    category: "Wallcovering",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FWallcovering%2Fpogo%20goat%2Fimage-thumb__46593__header_fullscreen_2x_jpg%2FMoooiWallcoveringMementoMoooi_PogoGoat_MO4052_Mood_Web_HR.webp&w=3840&q=80",
    itemname: "Pogo Goat Wallcovering ",
    brandName: "by moooi",
    price: "$250",
    availability: "In Stock",
    type: "Wall&Floor",
    category: "Wallcovering",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FWallcovering%2Fbearded%20leopard%2Fimage-thumb__14685__header_fullscreen_2x_jpg%2Fmoooiwallcoveringextinctanimals-beardedleopard-mo2053-m3.webp&w=3840&q=80",
    itemname: "Bearded Leopard Wallcovering ",
    brandName: "by moooi",
    price: "$250",
    availability: "In Stock",
    type: "Wall&Floor",
    category: "Wallcovering",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FRe-Cut%20Tiger%20from%20Tibet%2Fimage-thumb__40678__header_fullscreen_2x_jpg%2FTiger-from-Tibet-300DPI.webp&w=1080&q=80",
    itemname: "Tiger from Tibet ",
    brandName: "by Atelier Reserve",
    price: "$250",
    availability: "In Stock",
    type: "Wall&Floor",
    category: "Carpets",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FFluid%2Fimage-thumb__51558__header_fullscreen_2x_jpg%2FFluid-Dawn-200x300cm-v3.webp&w=750&q=80",
    itemname: "Fluid Carpet ",
    brandName: "by Rive Roshan",
    price: "$2372.00",
    availability: "In Stock",
    type: "Wall&Floor",
    category: "Carpets",
  },

  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FForest%20Floors%2Fimage-thumb__60723__header_fullscreen_2x_jpg%2FForrest-Floors-Landscape.webp&w=3840&q=80",
    itemname: "Forest Floors Carpet ",
    brandName: "by front",
    price: "$250",
    availability: "In Stock",
    type: "Wall&Floor",
    category: "Carpets",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FPollination%20of%20Hortensia%2Fimage-thumb__64764__header_fullscreen_2x_jpg%2FPOLLINATION-OF-HORTENSIA-CARPET-SPRING-200x300cm-300Dpi.webp&w=1080&q=80",
    itemname: "Pollination of Hortensia Carpet ",
    brandName: "by Andrés Reisinger",
    price: "$250",
    availability: "In Stock",
    type: "Wall&Floor",
    category: "Carpets",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FColour%20Dial%2Fimage-thumb__64959__header_fullscreen_2x_jpg%2FColourDial-Arc-Iridescence-300Dpi.webp&w=1080&q=80",
    itemname: "Colour Dial Carpet ",
    brandName: "by rive roshan",
    price: "$250",
    availability: "In Stock",
    type: "Wall&Floor",
    category: "Carpets",
  },
];

export let WallFloorHead = {
  title: "Wall & Floor",
  btn: ["All Wall & Floor", "Wallcovering", "Carpets"],
};
