export const BeddingBath = [
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBedding%2FBed%20Scarf%2FMenagerie%2Fimage-thumb__51143__header_fullscreen_2x_jpg%2F6934-MO-Menagerie-of-Extinct-Animals-Raven-XL-Scarf.webp&w=1080&q=80",
    itemname: "Menagerie of Extinct Animals Bed Scarf XL ",
    brandName:"BY MOOOI",
    price: "$250",
    availability: "In Stock",
    category: "Bedding",
    type: "BeddingBath",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBedding%2FBedspread%2FDodo%20Pavone%2Fimage-thumb__51138__header_fullscreen_2x_jpg%2F6933-MO-Dodo-Pavone-Bedspread-Ivory.webp&w=1080&q=80",
    itemname: "Embroidered Dodo Pavone Bedspread ",
    brandName:"BY MOOOI",
    price: "$250",
    availability: "In Stock",
    category: "Bedding",
    type: "BeddingBath",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBedding%2FBed%20Pillows%2FCalligraphy%20Bird%20Bed%20Pillows%2Fimage-thumb__53058__header_fullscreen_2x_jpg%2FCalligraphy-Bird_Blue_US_UV_King-2x36x20-10_Topshot-front.webp&w=1080&q=80",
    itemname: "Calligraphy Bird Bed Pillows ",
    brandName:"BY MOOOI",
    price: "$250",
    availability: "In Stock",
    category: "Bedding",
    type: "BeddingBath",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBedding%2FXL%20Pillows%2Fimage-thumb__53628__header_fullscreen_2x_jpg%2FMenagerie-Cushion-XL_Raven-10_Topshot.webp&w=3840&q=80",
    itemname: "Menagerie of Extinct Animals XL Pillow ",
    brandName:"BY MOOOI",
    price: "$250",
    availability: "In Stock",
    category: "Bedding",
    type: "BeddingBath",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBedding%2FDuvets%2FDuvets-colored-sheets%2Fimage-thumb__56613__header_fullscreen_2x_jpg%2FUmbrella-Squid_Silver_2P-10_Topshot-NEW_1.webp&w=1080&q=80",
    itemname: "Umbrella Squid Duvet Cover Set ",
    brandName:"BY MOOOI",
    price: "$250",
    availability: "In Stock",
    category: "Bedding",
    type: "BeddingBath",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBedding%2FDuvets%2FDuvets-colored-sheets%2Fimage-thumb__56623__header_fullscreen_2x_jpg%2FCalligraphy-Bird-Blue_Topshot.webp&w=1080&q=80",
    itemname: "Calligraphy Bird Duvet Cover Set ",
    brandName:"BY MOOOI",
    price: "$250",
    availability: "In Stock",
    category: "Bedding",
    type: "BeddingBath",
  },
  {
    src: "https://moooi.centracdn.net/client/dynamic/images/784_85fdde1766.jpg",
    itemname: "Embroidered Dodo Pavone Duvet Cover Set ",
    brandName:"BY MOOOI",
    price: "$250",
    availability: "In Stock",
    category: "Bedding",
    type: "BeddingBath",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBedding%2FDuvets%2FDuvets-colored-sheets%2Fimage-thumb__56638__header_fullscreen_2x_jpg%2FDodo-Pavone-Green_Topshot.webp&w=1080&q=80",
    itemname: "Dodo Pavone Duvet Cover Set",
    brandName:"BY MOOOI",
    price: "$250",
    availability: "In Stock",
    category: "Bedding",
    type: "BeddingBath",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBedding%2FDuvets%2FDuvets-colored-sheets%2Fimage-thumb__56643__header_fullscreen_2x_jpg%2FMenagerie-of-Extinct-Animals-Black_Topshot.webp&w=1080&q=80",
    itemname: "Menagerie of Extinct Animals Duvet Cover Set ",
    brandName:"BY MOOOI",
    price: "$250",
    availability: "In Stock",
    category: "Bedding",
    type: "BeddingBath",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBedding%2FBed%20Pillows%2FMenagerie%20Bed%20Pillows%2Fimage-thumb__53078__header_fullscreen_2x_jpg%2FMenagerie_Raven_US_UV_King-2x36x20-10_Topshot-front.webp&w=1080&q=80",
    itemname: "Menagerie of Extinct Animals ",
    brandName:"BY MOOOI",
    price: "$250",
    availability: "In Stock",
    category: "Bedding",
    type: "BeddingBath",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBath%2FTowel%2Fimage-thumb__65444__header_fullscreen_2x_jpg%2FDodo-Pavone-Towel_Stack-Topshot.webp&w=1080&q=80",
    itemname: "Dodo Pavone Towel ",
    brandName:"BY MOOOI",
    price: "$250",
    availability: "In Stock",
    category: "Bedding",
    type: "BeddingBath",
    category: "Bath"
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBath%2FBeach%20Towel%2Fimage-thumb__64384__header_fullscreen_2x_jpg%2FMenagerie-Beach-towel_Ivory_UV_UV_100x180-10_Topshot.webp&w=1080&q=80",
    itemname: "Menagerie of Extinct Animals Beach Towel ",
    brandName:"BY MOOOI",
    price: "$250",
    availability: "In Stock",
    type: "BeddingBath",
    category: "Bath"
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBath%2FKimono%2Fimage-thumb__64209__header_fullscreen_2x_jpg%2FMenagerie-Kimono_Raven_UV_UV--L-10_Topshot.webp&w=1080&q=80",
    itemname: "Menagerie of Extinct Animals Kimono ",
    brandName:"BY MOOOI",
    price: "$250",
    availability: "In Stock",
    type: "BeddingBath",
    category: "Bath"
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBath%2FBathrobe%2Fimage-thumb__64219__header_fullscreen_2x_jpg%2FDodo-Pavone-Bathrobe_White_UV_UV-10_Topshot.webp&w=1080&q=80",
    itemname: "Dodo Pavone Bathrobe ",
    brandName:"BY MOOOI",
    price: "$250",
    availability: "In Stock",
    type: "BeddingBath",
    category: "Bath"
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBath%2FTowel%2FMenagerie%20of%20Extinct%20Animals%20Towel%2Fimage-thumb__64294__header_fullscreen_2x_jpg%2FMenagerie-Towel_Ivory_UV_UV_100x150-10_Topshot.webp&w=1080&q=80",
    itemname: "Menagerie of Extinct Animals Towel ",
    brandName:"BY MOOOI",
    price: "$250",
    availability: "In Stock",
    type: "BeddingBath",
    category: "Bath"
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBedding%2FFitted%20Sheets%2FMenagerie%2Fimage-thumb__52883__header_fullscreen_2x_jpg%2FMenagerie_Green_US_UV_Mood_1.webp&w=1080&q=80",
    itemname: "Menagerie of Extinct Animals Fitted Sheet ",
    brandName:"BY MOOOI",
    price: "$250",
    availability: "In Stock",
    category: "Bedding",
    type: "BeddingBath",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBedding%2FFitted%20Sheets%2FEmbroidered%20Dodo%2Fimage-thumb__52478__header_fullscreen_2x_jpg%2FEmbroidered-Dodo_Ivory_US_UV_Mood.webp&w=1080&q=80",
    itemname: "Embroidered Dodo Pavone Fitted Sheet ",
    brandName:"BY MOOOI",
    price: "$250",
    availability: "In Stock",
    category: "Bedding",
    type: "BeddingBath",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBedding%2FFitted%20Sheets%2FUmbrella%20Squid%2Fimage-thumb__52483__header_fullscreen_2x_jpg%2FUmbrella-Squid_Silver_US_UV_Mood.webp&w=1080&q=80",
    itemname: "Umbrella Squid Fitted Sheet ",
    brandName:"BY MOOOI",
    price: "$250",
    availability: "In Stock",
    category: "Bedding",
    type: "BeddingBath",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBedding%2FFitted%20Sheets%2FDodo%20Pavone%2Fimage-thumb__52493__header_fullscreen_2x_jpg%2FDodo-Pavone_Dark-Sand_US_UV_Mood.webp&w=1080&q=80",
    itemname: "Dodo Pavone Fitted Sheet ",
    price: "$250",
    brandName:"BY MOOOI",
    availability: "In Stock",
    category: "Bedding",
    type: "BeddingBath",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBedding%2FFitted%20Sheets%2FCalligraphy%20Bird%2Fimage-thumb__52468__header_fullscreen_2x_jpg%2FCalligraphy-Bird_Blue_US_UV_Mood.webp&w=1080&q=80",
    itemname: "Calligraphy Bird Fitted Sheet ",
    brandName:"BY MOOOI",
    price: "$250",
    availability: "In Stock",
    category: "Bedding",
    type: "BeddingBath",
  },
];
export let BeddingBathhead = {
  title: "Bedding & bath",
  btn: ["All Bedding & Bath", "Bath", "Bedding"],
};
