export const Furniture = [
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FKisss%20Lounge%20Chair%2FPhotography%2FProduct%20Images%2FSingle%20Chair%20-%20Diving-3-623%2FPNG%2F83947%2Fimage-thumb__83947__header_fullscreen_2x_jpg%2FKisss-Chair-Divina-3-623_Product-SingleChair-1.webp&w=1200&q=80",
    itemname: "Kisss Lounge Chair ",
    brandName:"by Marcel Wanders",
    price: "$250",
    availability: "In Stock",
    type: "Furniture",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FContainer%2FContainer%20Bodhi%2F3401%2Fimage-thumb__3401__header_fullscreen_2x_jpg%2FContainer-Table_Bodhi-212-final.webp&w=3840&q=80 ",
    itemname:"Container Table ",
    brandName:"by Marcel Wanders",
    price: "$250",
    availability: "In Stock",
    type: "Furniture",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FHana%20Chair%20Dining%2FUn-Upholstered%2FTerracotta%2FPhotography%2FPng%20-%20Transparent%2F71844%2Fimage-thumb__71844__header_fullscreen_2x_jpg%2FTERRACOTA-HANA-CHAIR-BLACK_LEGS-FRONT.webp&w=1080&q=80",
    itemname: "Hana Chairs Un-Upholstered Set of 2  ",
    brandName:"by Marcel Wanders",
    price: "$250",
    availability: "In Stock",
    type: "Furniture",
  },
  
  // {
  //   src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FKnitty%20Lounge%20Chair%2F67784%2Fimage-thumb__67784__header_fullscreen_2x_jpg%2FKnitty-Lounge-Chair-front-angle-Mosaic-2-0222%20background.webp&w=750&q=80",
  //   itemname: "Menagerie of Extinct Animals Bed Scarf XL ",
  //   price: "$250",
  //   availability: "In Stock",
  //   type: "Furniture",
  // },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FHana%20Chair%20Dining%2FUpholstered%2FPhotography%2FPNG%2F73529%2Fimage-thumb__73529__header_fullscreen_2x_jpg%2FHana-Chair-Upholstered-product-32.webp&w=1080&q=80",
    itemname: "Hana Chair Upholstered ",
    brandName:"by Marcel Wanders",
    price: "$250",
    availability: "In Stock",
    type: "Furniture",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FAldora%2FAldora%20Vis%20a%20Vis%2FProduct%20Photography%2F75276%2Fimage-thumb__75276__header_fullscreen_2x_jpg%2FAldora_Vis_a_Vis_Leather_Front_Left.webp&w=3840&q=80",
    itemname: "Aldora Vis a Vis ",
    brandName:"by Marcel Wanders",
    price: "$250",
    availability: "In Stock",
    type: "Furniture",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FNo%20Screw%20No%20Glue%2FNo%20Screw%20No%20Glue%20Buffet%2Fimage-thumb__37899__header_fullscreen_2x_jpg%2FNo-Screw-No-Glue-Buffet-Mobile-parts-04.jpg&w=3840&q=80",
    itemname: "No Screw No Glue Buffet ",
    brandName:"by Marcel Wanders",
    price: "$250",
    availability: "In Stock",
    type: "Furniture",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FNo%20Screw%20No%20Glue%2FNo%20Screw%20No%20Glue%20Cabinet%2Fimage-thumb__40213__header_fullscreen_2x_jpg%2FNo-Screw-No-Glue-Cabinet-Front.jpg&w=1080&q=80",
    itemname: "No Screw No Glue Cabinet ",
    brandName:"by Marcel Wanders",
    price: "$250",
    availability: "In Stock",
    type: "Furniture",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FSmoke%20Series%2FSmoke%20Armchair%2F13028%2Fimage-thumb__13028__header_fullscreen_2x_jpg%2FSmoke-Armchair-Transparent.webp&w=1080&q=80",
    itemname: "Smoke Armchair ",
    brandName:"by Marcel Wanders",
    price: "$250",
    availability: "In Stock",
    type: "Furniture",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FSmoke%20Series%2FSmoke%20Dining%20chair%2F950%2Fimage-thumb__950__header_fullscreen_2x_jpg%2Fsmokedining-s-transparent.webp&w=1080&q=80",
    itemname: "Smoke Dining Chair ",
    brandName:"by Marcel Wanders",
    price: "$250",
    availability: "In Stock",
    type: "Furniture",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FAldora%2FAldora%20Chaise%20Longue%2FProduct%20Photography%20(old)%2F75521%2Fimage-thumb__75521__header_fullscreen_2x_jpg%2FAldora_sofa_chaise_longue_left_palette_product_front.webp&w=3840&q=80",
    itemname: "Aldora Chaise Longue ",
    brandName:"by Marcel Wanders",
    price: "$250",
    availability: "In Stock",
    type: "Furniture",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FAldora%2FAldora%20Sofa%2FProduct%20Photography%2F75226%2Fimage-thumb__75226__header_fullscreen_2x_jpg%2FAldora_Sofa_DODO_Front.webp&w=3840&q=80",
    itemname: "Aldora Sofa ",
    brandName:"by Marcel Wanders",
    price: "$250",
    availability: "In Stock",
    type: "Furniture",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FAmami%2FAmami%20Sofa%2F1285%2Fimage-thumb__1285__header_fullscreen_2x_jpg%2FAmami-Sofa-Brown.webp&w=3840&q=80",
    itemname: "Amami ",
    brandName:"by Marcel Wanders",
    price: "$250",
    availability: "In Stock",
    type: "Furniture",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FKnitty%20Lounge%20Chair%2F67784%2Fimage-thumb__67784__header_fullscreen_2x_jpg%2FKnitty-Lounge-Chair-front-angle-Mosaic-2-0222%20background.webp&w=750&q=80",
    itemname: " ",
    brandName:"by Marcel Wanders",
    price: "$250",
    availability: "In Stock",
    type: "Furniture",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBart%2FBart%20Swivel%2F37404%2Fimage-thumb__37404__header_fullscreen_2x_jpg%2FBart-Swivel-Blushing-Sloth-Wooly.webp&w=1080&q=80",
    itemname: "Bart Armchair ",
    brandName:"by Marcel Wanders",
    price: "$250",
    availability: "In Stock",
    type: "Furniture",
  },
  {
    src: "https://moooi.centracdn.net/client/dynamic/images/1093_200ed48666.jpg",
    itemname: "Charleston Sofa ",
    brandName:"by Marcel Wanders",
    price: "$250",
    availability: "In Stock",
    type: "Furniture",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCloud%20Sofa%2FCloud%20Sofa%2F16663%2Fimage-thumb__16663__header_fullscreen_2x_jpg%2Fclouds_velourgreen1.webp&w=3840&q=80",
    itemname: "Cloud Sofa ",
    brandName:"by Marcel Wanders",
    price: "$250",
    availability: "In Stock",
    type: "Furniture",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCocktail%20Chair%2F11580%2Fimage-thumb__11580__header_fullscreen_2x_jpg%2FCocktail_Chair_Bearder_Leopard_Front.webp&w=3840&q=80",
    itemname: "Cocktail Chair ",
    brandName:"by Marcel Wanders",
    price: "$250",
    availability: "In Stock",
    type: "Furniture",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCommon%20Comrades%2F1534%2Fimage-thumb__1534__header_fullscreen_2x_jpg%2Fcommon-comrades-all-6.webp&w=3840&q=80",
    itemname: "Common Comrades ",
    brandName:"by Marcel Wanders",
    price: "$250",
    availability: "In Stock",
    type: "Furniture",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FContainer%2FContainer%20Stool%2F61343%2Fimage-thumb__61343__header_fullscreen_2x_jpg%2FContainer-Stools.webp&w=1080&q=80",
    itemname: "Container Stool ",
    brandName:"by Marcel Wanders",
    price: "$250",
    availability: "In Stock",
    type: "Furniture",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FHana%2FHana%20Armchair%20Wingback%2F37399%2Fimage-thumb__37399__header_fullscreen_2x_jpg%2FHana-Wingback-Menagerie-of-Extinct-Animals.webp&w=1080&q=80",
    itemname: "Hana Armchair ",
    brandName:"by Marcel Wanders",
    price: "$250",
    availability: "In Stock",
    type: "Furniture",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FOblique%2FOblique%20Small%2F1806%2Fimage-thumb__1806__header_fullscreen_2x_jpg%2FOblique-S-Black-Photo.webp&w=1080&q=80",
    itemname: "Oblique ",
    brandName:"by Marcel Wanders",
    price: "$250",
    availability: "In Stock",
    type: "Furniture",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FThe%20Golden%20Chair%2Fimage-thumb__1639__header_fullscreen_2x_jpg%2Fgolden-chair-front.webp&w=1080&q=80",
    itemname: "The Golden Chair ",
    brandName:"by Marcel Wanders",
    price: "$250",
    availability: "In Stock",
    type: "Furniture",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FUrbanhike%2Fimage-thumb__1959__header_fullscreen_2x_jpg%2Furbanhike.webp&w=1080&q=80",
    itemname: "Urbanhike ",
    brandName:"by Marcel Wanders",
    price: "$250",
    availability: "In Stock",
    type: "Furniture",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FZio%2FZio%20Buffet%2Fimage-thumb__15622__header_fullscreen_2x_jpg%2Fzio_buffet_cinnamon-drawer-open.webp&w=3840&q=80",
    itemname: "Zio Buffet ",
    brandName:"by Marcel Wanders",
    price: "$250",
    availability: "In Stock",
    type: "Furniture",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FZio%2FZio%20Dining%20Chair%2Fimage-thumb__30194__header_fullscreen_2x_jpg%2FZio-Dining-Chair-Spectrum-Terracotta-White-wash-front.webp&w=1080&q=80",
    itemname: "Zio Dining Chair ",
    brandName:"by Marcel Wanders",
    price: "$250",
    availability: "In Stock",
    type: "Furniture",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FZio%2FZio%20Dining%20Table%2FZio%20Dining%20Table%20310%2Fimage-thumb__4046__header_fullscreen_2x_jpg%2FZio-Table-Composition-310-2.webp&w=3840&q=80",
    itemname: "Zio Dining Table ",
    brandName:"by Marcel Wanders",
    price: "$250",
    availability: "In Stock",
    type: "Furniture",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FZio%2FZio%20Footstool%2Fimage-thumb__4146__header_fullscreen_2x_jpg%2Fzio-footstool-manga.webp&w=1080&q=80",
    itemname: "Zio Dining Chair ",
    brandName:"by Marcel Wanders",
    price: "$250",
    availability: "In Stock",
    type: "Furniture",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FZio%2FZio%20Lounge%20Chair%2Fimage-thumb__30154__header_fullscreen_2x_jpg%2FZio-Lounge-Chair-Spectrum-Brown-Cinnamon-front-view.webp&w=1080&q=80",
    itemname: "Zio Lounge Chair ",
    brandName:"by Marcel Wanders",
    price: "$250",
    availability: "In Stock",
    type: "Furniture",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FLiberty%2FLiberty%20Table%2F1654%2Fimage-thumb__1654__header_fullscreen_2x_jpg%2FLiberty-Table-by-Joep-van-Lieshout-1.webp&w=3840&q=80",
    itemname: "Liberty Table ",
    brandName:"by Marcel Wanders",
    price: "$250",
    availability: "In Stock",
    type: "Furniture",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FO%2F16965%2Fimage-thumb__16965__header_fullscreen_2x_jpg%2FO_front-view.webp&w=1080&q=80",
    itemname:"O.",
    brandName:"by Marcel Wanders",
    price: "$250",
    availability: "In Stock",
    type: "Furniture",
  },
];

export let Furnitureobj = {
  title: "Furniture",
  btn: ["All Furniture", "Seating", "Storage", "Tables"],
};
